# Generated by Django 4.2 on 2023-05-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=100)),
                ('x_min', models.IntegerField()),
                ('y_min', models.IntegerField()),
                ('x_max', models.IntegerField()),
                ('Y_max', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('car_type', models.CharField(max_length=100)),
                ('purchase_date', models.CharField(max_length=50)),
                ('number_of_owners', models.IntegerField()),
                ('accident_history', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('km_reading', models.IntegerField()),
            ],
        ),
    ]
