# Generated by Django 4.2 on 2023-05-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetail',
            old_name='Y_max',
            new_name='y_max',
        ),
    ]
