# Generated by Django 4.2 on 2023-05-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0002_rename_y_max_cardetail_y_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='accident_history',
            field=models.CharField(max_length=5),
        ),
    ]
